version: '3.8'

services:
  # Streamlit application
  titanic-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../src:/app/src
      - ../streamlit_app:/app/streamlit_app
    networks:
      - titanic-network

networks:
  titanic-network:
    driver: bridge
